drrkkm's homework
DafeMipt213/algorithms_1st pull request #35
Opened 2023-03-31 19:01 UTC by drrkkm

First three tasks with tests.

2023-04-08 09:33 UTC, LostPointer requested changes

2023-04-08 09:33 UTC, LostPointer commented on task_01/src/stack.cpp
> +#include <cstddef>
удали этот файл, тут нет кода

2023-04-08 09:33 UTC, LostPointer commented on task_01/src/stack.hpp
> +  Dot(Dot *finish1, T value1) : back(finish1), value(value1) {}
finish1 не красивое название переменной, тут можно назвать просто back

2023-04-08 09:33 UTC, LostPointer commented on task_01/src/stack.hpp
> +struct Dot {
так себе имя структуры, не очень понятно что такое Dot, что такое точка?

2023-04-08 09:33 UTC, LostPointer commented on task_01/src/stack.hpp
> +    auto temp = std::unique_ptr<Dot<T>>(finish_);
а зачем тут делаешь unique_ptr? только для того что бы удалилось потом? тогда лучше либо везде использовать умные указатели, либо испальзовать только сырые указатели и вручную удалять память

2023-04-08 09:33 UTC, LostPointer commented on task_02/src/heap.hpp
> +void MinHeap<T>::ShiftUp(int index) {
index не может быть меньше нуля, используй size_t, а не int

2023-04-08 09:33 UTC, LostPointer commented on task_03/src/sort.hpp
> +  for (int k = 0; k < array.size(); k++) {
заюзай std::swap, это быстрее чем копировать поэлементно

2023-05-20 08:58 UTC, drrkkm commented
Тесты не прошли потому, что я начала реализовывать дерево но до конца не закончила

2023-05-26 20:03 UTC, LostPointer requested changes

2023-05-26 20:03 UTC, LostPointer commented on task_01/src/stack.hpp
> +    if (start_) delete start_;
удаляешь только начало и конец, а середину не удаляешь, ну и если у тебя 1 элемент, то удалишь его 2 раза

2023-05-26 20:03 UTC, LostPointer commented on task_01/src/stack.hpp
> +    auto temp = new Node<T>(finish_, 0);
создаешь элемент, потом конечно удаляешь его, но тот что был в конце все равно не удаляется(

может это хотела: auto temp = finish_;

2023-05-26 20:03 UTC, LostPointer commented on task_01/src/stack.hpp
> +struct Node {
если запихнуть как внутрений класс Stack то можно сделать структурой, без приватных полей

2023-05-26 20:03 UTC, LostPointer commented on task_01/src/stack.hpp
> +    auto tmp = finish_->GetBack()->GetNext();
тут у тебя создастся новый указатель и ты его занулишь, а вот указатель next_ у предпоследнего элемента незанулится

и кстати проще стэк сделать только с указателем на предидущий элемент, меньше менять нужно будет

2023-05-26 20:03 UTC, LostPointer commented on task_02/src/heap.hpp
> +  if (2 * index + 1 > data_.size() - 1 || index > data_.size())
много раз используется 2 * index + 1 лучше вынести в отдельную переменную, так же как и 2 * index + 2

2023-05-26 20:03 UTC, LostPointer commented on task_02/src/heap.hpp
> +  if (2 * index + 1 > data_.size() - 1 || index > data_.size())
это и сильно улучшит читаемость кода

2023-05-26 20:03 UTC, LostPointer commented on task_02/src/heap.hpp
> +  if (data_.size() > 0) {
этот if всегда будет выполняться, у тебя уже кидается исключение когда стэк пустой

2023-05-26 20:03 UTC, LostPointer commented on task_03/src/sort.hpp
> +void Merge(std::vector<T> &data, int start, int center, int finish) {
для индексов лучше использовать size_t или unsigned int

2023-05-26 20:03 UTC, LostPointer commented on task_04/src/order_statistics.hpp
> +  else return GetOrderStatistics(third,n -first.size()- second.size());
кажется тут лучше будет выглядеть  GetOrderStatistics(third, third.size());

2025-04-06 18:32 UTC, closed without merging